---
    - name: Deploy New Website
      hosts: web_servers
      become: true
      tasks:
            - include_tasks: tasks/create_website_user.yml

            - include_tasks: tasks/create_website_database.yml

            - include_tasks: tasks/create_configuration_files.yml

            - include_tasks: tasks/unpack_wordpress.yml

            - include_tasks: tasks/restart_services.yml
